version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      PG_URL: jdbc:postgresql://postgres:5432/postgres
      PG_USERNAME: postgres
      PG_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: dev
      PG_SCHEMA: task
      JWT_SECRET: PRh7vkFBAn53ZI2YK5/Y9xaXgGR6sQ3uCUMwO0/x/5Y=
      JWT_EXPIRATION_TIME: 86400000
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
