CREATE TABLE task(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL UNIQUE,
    description TEXT NOT NULL,
    status VARCHAR(255) NOT NULL,
    priority VARCHAR(255) NOT NULL,
    author_id BIGINT NOT NULL,
    performer_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE comment(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    author_id BIGINT NOT NULL,
    task_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE user_info(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

ALTER TABLE
    "task" ADD CONSTRAINT "task_author_id_foreign" FOREIGN KEY("author_id") REFERENCES "user_info"("id");
ALTER TABLE
    "comment" ADD CONSTRAINT "comment_author_id_foreign" FOREIGN KEY("author_id") REFERENCES "user_info"("id");
ALTER TABLE
    "task" ADD CONSTRAINT "task_performer_id_foreign" FOREIGN KEY("performer_id") REFERENCES "user_info"("id");
ALTER TABLE
    "comment" ADD CONSTRAINT "comment_task_id_foreign" FOREIGN KEY("task_id") REFERENCES "task"("id");

